-- CREATE TABLE Pet (
--     PetID INT NOT NULL,
--     name VARCHAR(150),
--     age VARCHAR(30),
--     gender VARCHAR(6),
--     breed VARCHAR(150),
--     hair_color VARCHAR(100),
--     sterilisation VARCHAR(6),
--     size FLOAT,
--     behaviour VARCHAR(300),
--     foundDate DATE,
--     CONSTRAINT PK_Pet PRIMARY KEY (PetID),
-- );
